services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - ./var/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=letuspass

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    depends_on:
      - postgres
    environment:
      - GIN_MODE=release
      - LOG_FILE=./logs/backend.log
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=letuspass
      - DB_PORT=5432
      - DB_SSL_MODE=disable
      - DB_TIME_ZONE=UTC
      - SESSION_TOKEN_COOKIE_NAME=session_token
      - SESSION_TOKEN_EXPIRE_SECONDS=86400
      - CORS_ALLOW_ORIGINS=http://localhost:3000

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_BASE_URL: http://localhost:8080
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
