FROM golang:1.22-alpine

WORKDIR /app
COPY . .

RUN go env -w GOCACHE=/cache/go-cache
RUN go env -w GOMODCACHE=/cache/gomod-cache

RUN --mount=type=cache,target=/cache/gomod-cache \
 go mod download

ENTRYPOINT ["go", "test", "./..."]
