/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * LetusPass REST API
 * Project description at https://github.com/berk-karaal/letuspass
 * OpenAPI spec version: 0.0.1
 */
export type ListVaultAuditLogsParams = {
  /**
   * Page number
   */
  page?: number;
  /**
   * Item count per page
   */
  page_size?: number;
};

export type ListVaultItemsOrdering =
  (typeof ListVaultItemsOrdering)[keyof typeof ListVaultItemsOrdering];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListVaultItemsOrdering = {
  title: "title",
  "-title": "-title",
  created_at: "created_at",
  "-created_at": "-created_at",
} as const;

export type ListVaultItemsParams = {
  /**
   * Page number
   */
  page?: number;
  /**
   * Item count per page
   */
  page_size?: number;
  /**
   * Ordering
   */
  ordering?: ListVaultItemsOrdering;
  /**
   * Search by title
   */
  title?: string;
};

export type ListVaultsOrdering =
  (typeof ListVaultsOrdering)[keyof typeof ListVaultsOrdering];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListVaultsOrdering = {
  name: "name",
  "-name": "-name",
  created_at: "created_at",
  "-created_at": "-created_at",
} as const;

export type ListVaultsParams = {
  /**
   * Page number
   */
  page?: number;
  /**
   * Item count per page
   */
  page_size?: number;
  /**
   * Ordering
   */
  ordering?: ListVaultsOrdering;
};

export type GetUserByEmailParams = {
  /**
   * Email of the user
   */
  email: string;
};

export interface SchemasNotFoundResponse {
  error: string;
}

export interface SchemasBadRequestResponse {
  error: string;
}

export interface PaginationStandardPaginationResponseControllersHandleVaultsListVaultResponseItem {
  count: number;
  results: ControllersHandleVaultsListVaultResponseItem[];
}

export interface PaginationStandardPaginationResponseControllersHandleVaultAuditLogsListAuditLogResponseItem {
  count: number;
  results: ControllersHandleVaultAuditLogsListAuditLogResponseItem[];
}

export type ModelsAuditLogAction =
  (typeof ModelsAuditLogAction)[keyof typeof ModelsAuditLogAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsAuditLogAction = {
  vault_create: "vault_create",
  vault_rename: "vault_rename",
  vault_delete: "vault_delete",
  vault_add_user: "vault_add_user",
  vault_remove_user: "vault_remove_user",
  vault_user_left: "vault_user_left",
  vault_item_create: "vault_item_create",
  vault_item_update: "vault_item_update",
  vault_item_delete: "vault_item_delete",
} as const;

export interface ControllersHandleVaultsMyKeyVaultKeyResponse {
  encrypted_vault_key: string;
  encryption_iv: string;
  inviter_user_id: number;
  inviter_user_public_key: string;
  key_owner_user_id: number;
}

export interface ControllersHandleVaultsManageRenameRenameVaultResponse {
  name: string;
}

export interface ControllersHandleVaultsManageRenameRenameVaultRequest {
  name: string;
}

export interface ControllersHandleVaultsManageRemoveUserRemoveUserRequest {
  user_id: number;
}

export interface ControllersHandleVaultsManageListUsersUsersResponseItem {
  email: string;
  id: number;
  permissions: string[];
}

export interface ControllersHandleVaultsManageAddUserAddUserRequest {
  email: string;
  encrypted_vault_key: string;
  permissions: string[];
  vault_key_encryption_iv: string;
}

export interface ControllersHandleVaultsListVaultResponseItem {
  created_at: string;
  id: number;
  name: string;
  updated_at: string;
}

export interface ControllersHandleVaultsCreateVaultCreateResponse {
  id: number;
  name: string;
}

export interface ControllersHandleVaultsCreateVaultCreateRequest {
  encrypted_vault_key: string;
  encryption_iv: string;
  name: string;
}

export interface ControllersHandleVaultItemsUpdateVaultItemUpdateResponse {
  encrypted_note: string;
  encrypted_password: string;
  encrypted_username: string;
  id: number;
  title: string;
}

export interface ControllersHandleVaultItemsUpdateVaultItemUpdateRequest {
  encrypted_note?: string;
  encrypted_password?: string;
  encrypted_username?: string;
  title: string;
}

export interface ControllersHandleVaultItemsRetrieveVaultItemRetrieveResponse {
  encrypted_note: string;
  encrypted_password: string;
  encrypted_username: string;
  encryption_iv: string;
  id: number;
  title: string;
  updated_at: string;
}

export interface ControllersHandleVaultItemsListVaultItemResponseItem {
  id: number;
  title: string;
}

export interface PaginationStandardPaginationResponseControllersHandleVaultItemsListVaultItemResponseItem {
  count: number;
  results: ControllersHandleVaultItemsListVaultItemResponseItem[];
}

export interface ControllersHandleVaultItemsCreateVaultItemCreateResponse {
  encrypted_note: string;
  encrypted_password: string;
  encrypted_username: string;
  encryption_iv: string;
  id: number;
  title: string;
}

export interface ControllersHandleVaultItemsCreateVaultItemCreateRequest {
  encrypted_note?: string;
  encrypted_password?: string;
  encrypted_username?: string;
  encryption_iv: string;
  title: string;
}

export interface ControllersHandleVaultAuditLogsListVaultItemData {
  id: number;
  title: string;
}

export interface ControllersHandleVaultAuditLogsListUserData {
  email: string;
  id: number;
}

export type ControllersHandleVaultAuditLogsListAuditLogResponseItemActionData =
  { [key: string]: unknown };

export interface ControllersHandleVaultAuditLogsListAuditLogResponseItem {
  action_code: ModelsAuditLogAction;
  action_data: ControllersHandleVaultAuditLogsListAuditLogResponseItemActionData;
  created_at: string;
  id: number;
  user: ControllersHandleVaultAuditLogsListUserData;
  vault_item?: ControllersHandleVaultAuditLogsListVaultItemData;
}

export interface ControllersHandleUsersMeMeResponse {
  email: string;
  name: string;
}

export interface ControllersHandleMetricsStatusMetricsStatusResponse {
  status: string;
}

export interface ControllersHandleGetUserByEmailUserResponse {
  email: string;
  name: string;
  public_key: string;
}

export interface ControllersHandleAuthRegisterRegisterRequest {
  email: string;
  key_derivation_salt: string;
  name: string;
  password: string;
  public_key: string;
}

export interface ControllersHandleAuthLoginLoginResponse {
  email: string;
  key_derivation_salt: string;
  name: string;
}

export interface ControllersHandleAuthLoginLoginRequest {
  email: string;
  password: string;
}

export interface BodybinderValidationErrorResponseItem {
  field: string;
  reason: string;
}

export interface BodybinderValidationErrorResponse {
  errors: BodybinderValidationErrorResponseItem[];
}
