// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login user",
                "operationId": "authLogin",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.HandleAuthLogin.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.HandleAuthLogin.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.BadRequestResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/bodybinder.validationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout user",
                "operationId": "authLogout",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register user",
                "operationId": "authRegister",
                "parameters": [
                    {
                        "description": "User Registration Data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.HandleAuthRegister.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.BadRequestResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/bodybinder.validationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/metrics/status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Get status of the server",
                "operationId": "getServerStatus",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.HandleMetricsStatus.MetricsStatusResponse"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get currently logged-in user",
                "operationId": "getCurrentUser",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.HandleUsersMe.MeResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/vaults": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "List vaults that user has read access to",
                "operationId": "listVaults",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Item count per page",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "name",
                            "-name",
                            "created_at",
                            "-created_at"
                        ],
                        "type": "string",
                        "description": "Ordering",
                        "name": "ordering",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pagination.StandardPaginationResponse-controllers_HandleVaultsList_VaultResponseItem"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "Create a new vault",
                "operationId": "createVault",
                "parameters": [
                    {
                        "description": "New vault data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.HandleVaultsCreate.VaultCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controllers.HandleVaultsCreate.VaultCreateResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/bodybinder.validationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/vaults/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "Retrieve vault by id",
                "operationId": "retrieveVault",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.HandleVaultsCreate.VaultCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "tags": [
                    "vaults"
                ],
                "summary": "Delete vault by id",
                "operationId": "deleteVault",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/vaults/{id}/items": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vault items"
                ],
                "summary": "List items of a vault",
                "operationId": "listVaultItems",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Item count per page",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "title",
                            "-title",
                            "created_at",
                            "-created_at"
                        ],
                        "type": "string",
                        "description": "Ordering",
                        "name": "ordering",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by title",
                        "name": "title",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pagination.StandardPaginationResponse-controllers_HandleVaultItemsList_VaultItemResponseItem"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vault items"
                ],
                "summary": "Create a new vault item",
                "operationId": "createVaultItem",
                "parameters": [
                    {
                        "description": "New vault item data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.HandleVaultItemsCreate.VaultItemCreateRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "Vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controllers.HandleVaultItemsCreate.VaultItemCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/bodybinder.validationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/vaults/{id}/items/{itemId}": {
            "get": {
                "tags": [
                    "vault items"
                ],
                "summary": "Retrieve a new vault item",
                "operationId": "retrieveVaultItem",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Vault Item id",
                        "name": "itemId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.HandleVaultItemsRetrieve.VaultItemRetrieveResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.NotFoundResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/bodybinder.validationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vault items"
                ],
                "summary": "Update a new vault item",
                "operationId": "updateVaultItem",
                "parameters": [
                    {
                        "description": "New vault item data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.HandleVaultItemsUpdate.VaultItemUpdateRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "Vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Vault Item id",
                        "name": "itemId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.HandleVaultItemsUpdate.VaultItemUpdateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.NotFoundResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/bodybinder.validationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "tags": [
                    "vault items"
                ],
                "summary": "Delete a vault item",
                "operationId": "deleteVaultItem",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Vault Item id",
                        "name": "itemId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.NotFoundResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/bodybinder.validationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/vaults/{id}/key": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "Retrieve current user's vault key record for the vault",
                "operationId": "retrieveMyVaultKey",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.HandleVaultsMyKey.VaultKeyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/vaults/{id}/manage/add-user": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vault manage"
                ],
                "summary": "Add user to vault",
                "operationId": "addUserToVault",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New user data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.HandleVaultsManageAddUser.AddUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/bodybinder.validationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/vaults/{id}/manage/users": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vault manage"
                ],
                "summary": "List users who have access to vault",
                "operationId": "listVaultUsers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.HandleVaultsManageListUsers.UsersResponseItem"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "tags": [
                    "vault manage"
                ],
                "summary": "Remove user from vault",
                "operationId": "removeUserFromVault",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ID of the user which will be removed",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.HandleVaultsManageRemoveUser.RemoveUserRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/bodybinder.validationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/vaults/{id}/my-permissions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "List current user's permission on vault",
                "operationId": "listMyVaultPermissions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vault id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.BadRequestResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "bodybinder.validationErrorResponse": {
            "type": "object",
            "required": [
                "errors"
            ],
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/bodybinder.validationErrorResponseItem"
                    }
                }
            }
        },
        "bodybinder.validationErrorResponseItem": {
            "type": "object",
            "required": [
                "field",
                "reason"
            ],
            "properties": {
                "field": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "controllers.HandleAuthLogin.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "controllers.HandleAuthLogin.LoginResponse": {
            "type": "object",
            "required": [
                "email",
                "key_derivation_salt",
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "key_derivation_salt": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "controllers.HandleAuthRegister.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "key_derivation_salt",
                "name",
                "password",
                "public_key"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "key_derivation_salt": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "public_key": {
                    "type": "string"
                }
            }
        },
        "controllers.HandleMetricsStatus.MetricsStatusResponse": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "controllers.HandleUsersMe.MeResponse": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "controllers.HandleVaultItemsCreate.VaultItemCreateRequest": {
            "type": "object",
            "required": [
                "encryption_iv",
                "title"
            ],
            "properties": {
                "encrypted_note": {
                    "type": "string"
                },
                "encrypted_password": {
                    "type": "string"
                },
                "encrypted_username": {
                    "type": "string"
                },
                "encryption_iv": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "controllers.HandleVaultItemsCreate.VaultItemCreateResponse": {
            "type": "object",
            "required": [
                "encrypted_note",
                "encrypted_password",
                "encrypted_username",
                "encryption_iv",
                "id",
                "title"
            ],
            "properties": {
                "encrypted_note": {
                    "type": "string"
                },
                "encrypted_password": {
                    "type": "string"
                },
                "encrypted_username": {
                    "type": "string"
                },
                "encryption_iv": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "controllers.HandleVaultItemsList.VaultItemResponseItem": {
            "type": "object",
            "required": [
                "id",
                "title"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "controllers.HandleVaultItemsRetrieve.VaultItemRetrieveResponse": {
            "type": "object",
            "required": [
                "encrypted_note",
                "encrypted_password",
                "encrypted_username",
                "encryption_iv",
                "id",
                "title",
                "updated_at"
            ],
            "properties": {
                "encrypted_note": {
                    "type": "string"
                },
                "encrypted_password": {
                    "type": "string"
                },
                "encrypted_username": {
                    "type": "string"
                },
                "encryption_iv": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "controllers.HandleVaultItemsUpdate.VaultItemUpdateRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "encrypted_note": {
                    "type": "string"
                },
                "encrypted_password": {
                    "type": "string"
                },
                "encrypted_username": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "controllers.HandleVaultItemsUpdate.VaultItemUpdateResponse": {
            "type": "object",
            "required": [
                "encrypted_note",
                "encrypted_password",
                "encrypted_username",
                "id",
                "title"
            ],
            "properties": {
                "encrypted_note": {
                    "type": "string"
                },
                "encrypted_password": {
                    "type": "string"
                },
                "encrypted_username": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "controllers.HandleVaultsCreate.VaultCreateRequest": {
            "type": "object",
            "required": [
                "encrypted_vault_key",
                "encryption_iv",
                "name"
            ],
            "properties": {
                "encrypted_vault_key": {
                    "type": "string"
                },
                "encryption_iv": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "controllers.HandleVaultsCreate.VaultCreateResponse": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "controllers.HandleVaultsList.VaultResponseItem": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "name",
                "updated_at"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "controllers.HandleVaultsManageAddUser.AddUserRequest": {
            "type": "object",
            "required": [
                "email",
                "permissions"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "controllers.HandleVaultsManageListUsers.UsersResponseItem": {
            "type": "object",
            "required": [
                "email",
                "permissions"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "controllers.HandleVaultsManageRemoveUser.RemoveUserRequest": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "controllers.HandleVaultsMyKey.VaultKeyResponse": {
            "type": "object",
            "required": [
                "encrypted_vault_key",
                "encryption_iv",
                "inviter_user_id",
                "inviter_user_public_key",
                "key_owner_user_id"
            ],
            "properties": {
                "encrypted_vault_key": {
                    "type": "string"
                },
                "encryption_iv": {
                    "type": "string"
                },
                "inviter_user_id": {
                    "type": "integer"
                },
                "inviter_user_public_key": {
                    "type": "string"
                },
                "key_owner_user_id": {
                    "type": "integer"
                }
            }
        },
        "pagination.StandardPaginationResponse-controllers_HandleVaultItemsList_VaultItemResponseItem": {
            "type": "object",
            "required": [
                "count",
                "results"
            ],
            "properties": {
                "count": {
                    "type": "integer"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.HandleVaultItemsList.VaultItemResponseItem"
                    }
                }
            }
        },
        "pagination.StandardPaginationResponse-controllers_HandleVaultsList_VaultResponseItem": {
            "type": "object",
            "required": [
                "count",
                "results"
            ],
            "properties": {
                "count": {
                    "type": "integer"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.HandleVaultsList.VaultResponseItem"
                    }
                }
            }
        },
        "schemas.BadRequestResponse": {
            "type": "object",
            "required": [
                "error"
            ],
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "schemas.NotFoundResponse": {
            "type": "object",
            "required": [
                "error"
            ],
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "LetusPass REST API",
	Description:      "Project description at https://github.com/berk-karaal/letuspass",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
